language: python

matrix:
  include:
    - python: 3.8
      arch: amd64
    - python: 3.8
      arch: arm64
install: pip install tox tox-travis
script: tox
sudo: false
env:
  global:
    secure: RTfsNexYTJSFaneE/gxYmQbSkvkIJaXzYzVD9lVeo2VxXAalwmGdmnUZTnH9bJj8CZVBYfudpb0m1OeCNuKdSsBn3vZwApr7kqg1Tr9eP2w2at8Fm6D4rAbN5D4D8bh5N5gUCRy2Wi0oTlYE4bbW80gnB3zauFxytDf0sqqbnW0=
